### ISSUE TITLE
NPM package name

### ISSUE THREAD

**Issue by Elliot-Alexander** [Elliot-Alexander/vaul-vue#5]
Unfortunately, `vaul-vue`, `vue-vaul` and `vue-vaul-drawer` are all taken with minimal (if any) implementation. Should we publish this as `vaul-vue` under an organisation scope? Zernonia from the Radix Vue team has expressed interest in having a scope for packages related to the tools and libraries they maintain, does it make sense for us to wait and use that scope?

**Comment by Elliot-Alexander** [comment]
Discussion was started in [this issue here](https://github.com/radix-vue/shadcn-vue/issues/220)

**Comment by connerblanton** [comment]
I reached out to @baradghimire (current owner of the `vaul-vue` name on npm) and he has agreed to transfer over the name some time tomorrow!

**Comment by Elliot-Alexander** [comment]
Were we able to secure that name?

**Comment by baradghimire** [comment]
Yep, I've transferred ownership of the `vaul-vue` name on npm to @connerblanton :)

**Comment by connerblanton** [comment]
Huge thanks to @baradghimire!

@Elliot-Alexander let me know your npm username and I will add you as a maintainer

**Comment by Elliot-Alexander** [comment]
Thank you so much @baradghimire . Really appreciate you donating that name. My npm username is elliotalexander

**Comment by connerblanton** [comment]
Invite sent!

**Comment by Elliot-Alexander** [comment]
Accepted, will try to have the release automations set up by the end of the week :)
